---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-maven-repository
  labels:
    app: sample-maven-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-maven-repository
  template:
    metadata:
      labels:
        app: sample-maven-repository
    spec:
      containers:
        - image: ko://github.com/cirocosta/sample-maven-repository
          name: app
